version: '3.7'
services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/web/Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY="base64:C4fgHRFQNftTAT8JGuvkIW9qQoEgtynKs8fus1i0a+0="
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000

      - LOG_CHANNEL=stack

      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test_project
      - DB_USERNAME=root
      - DB_PASSWORD=

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

    ports:
      - "8000:8000"
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test_project
    ports:
      - "3306:3306"
